name: Benchmark
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8
      - uses: actions/cache@v3
        name: "Cache local Maven repository"
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            ${{ runner.os }}-maven-
            
      - name: Run benchmark for h1server
        run: |
          cd server-http
          mvn clean package
          java -jar server-http/target/http-server.jar

      - name: Run benchmark for h1client
        run: |
          cd client
          mvn clean package -Ph1
          java -jar client/target/benchmark-client-h1.jar