name: Benchmark
on:
  push:
    branches:
      - main
permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write
jobs:
  benchmark:
    name: benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Run the Maven
        run: mvn clean package -Ph1

      - name: Run benchmark for h1server
        run: |
          java -jar server-http/target/http-server.jar & sleep 10

      - name: Run benchmark for h1client
        run: |
          java -jar client/target/benchmark-client-h1.jar -warmupIterations 3 -measurementIterations 1 -forks 1 -benchmarkName h1 -version 1.0

#      - name: Checkout code
#        uses: actions/checkout@v2
      - name: Push benchmark result
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout --orphan benchmark-result
          git rm -rf .
          git pull origin benchmark-result
          git add 1.0/
          git commit -m "Add benchmark result"
          git push origin benchmark-result:benchmark-result

#      - name: Store benchmark result
#        uses: benchmark-action/github-action-benchmark@v1
#        with:
#          name: JMH Benchmark
#          tool: 'jmh'
#          output-file-path: jmh_result.json
#          # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t/github-action-not-triggering-gh-pages-upon-push/16096
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          auto-push: true
#          # Show alert with commit comment on detecting possible performance regression
#          alert-threshold: '200%'
#          comment-on-alert: true
#          fail-on-alert: true
