name: Benchmark
on:
  push:
    branches:
      - main

jobs:
  build:
    name: build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Run the Maven
        run: mvn clean package -Ph1

      - name: Run benchmark for h1server
        run: |
          java -jar server-http/target/http-server.jar

      - name: Run benchmark for h1client
        run: |
          java -jar client/target/benchmark-client-h1.jar

#      - uses: actions/setup-java@v3
#        with:
#          distribution: 'zulu'
#          java-version: 8
#      - uses: actions/cache@v3
#        name: "Cache local Maven repository"
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-${{ github.run_id }}
#          restore-keys: |
#            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#            ${{ runner.os }}-maven-
#      - name: build http server
#        run: |
#          mvn clean package
#
#      - name: build http client
#        run: |
#          mvn clean package -Ph1
